# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7523e95a6c59be0d6879ccdd6a316b888477ae06d2c1ab86784f15bb7954f1ddd9a292d9b08f5bc6b8ebfca916e553be8f93984e9b955fb7397a163adfcdd055

test:
  secret_key_base: d599fc5d83f2a499d04304bf2522a438828fe5086ef5424e3d792f5e3451c486958a350534bbb269f9d70d8d4dbae0ded2b4f9878c4dfd7a1ec1d448e41184cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
